// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Few70QbJ6qXBcTLnipj6rJz5Xob0_TM',
    appId: '1:187115929867:web:3076696af60822aab1220e',
    messagingSenderId: '187115929867',
    projectId: 'notes-72b93',
    authDomain: 'notes-72b93.firebaseapp.com',
    storageBucket: 'notes-72b93.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-0lSpIOst52P1qR-gJNrrL6T7iQHsQm0',
    appId: '1:187115929867:android:220e783cca0787ecb1220e',
    messagingSenderId: '187115929867',
    projectId: 'notes-72b93',
    storageBucket: 'notes-72b93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9s8VHDlircbJfsHldsrH7gPKmzI6MqAk',
    appId: '1:187115929867:ios:704841769d471f53b1220e',
    messagingSenderId: '187115929867',
    projectId: 'notes-72b93',
    storageBucket: 'notes-72b93.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );
}
